name: branta
description: A Branta SDK for Dart.
version: 3.2.0
repository: https://github.com/BrantaOps/branta-dart

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  http: ^1.6.0
  uuid: ^4.4.2

dev_dependencies:
  coverage: ^1.0.0
  lints: ^6.0.0
  test: ^1.25.6
